add check hash

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -11,6 +11,21 @@ inputs:
 runs:
   using: "composite"
   steps: 
+    - name: Check Hash
+    - run: |
+        head_hash=$(git rev-parse HEAD)
+        current_hash=${GITHUB_SHA}
+        echo "HEAD hash=$head_hash"
+        echo "ACTION hash=$current_hash"
+        if [ $head_hash = $current_hash ]; then
+           echo "hash check ok!"
+        else
+           echo "Looks like miss commits, aborting .."
+           exit 1
+        fi    
+      shell: bash
+
+    - name: Init Envs
     - run: |
         echo ${{ inputs.env-json-base64 }} | base64 --decode > data.json
         CONTAINERREGISTRY=$(jq -r '.REGISTRY' data.json)
@@ -26,5 +41,6 @@ runs:
         TAG=$(echo $GITHUBSHA | cut -c1-6)
         echo "::set-env name=TAG::$TAG"
 
+        echo "init environment variables ok!"
       shell: bash
 
